-- ============================================================
-- RPT_DMSK_HOLDERS
-- shareholder/QFII 持仓 (特殊报表) (quarterly)
-- chunky qfii_client 实际使用; extra_filters: HOLDER_NEWTYPE=QFII, HOLDNUM_CHANGE_NAME, END_DATE
-- 样本行数: 200, 字段数: 34
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_dmsk_holders (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  RANK INTEGER NOT NULL,
  HOLDER_CODE VARCHAR NOT NULL,
  HOLDER_NAME VARCHAR NOT NULL,
  HOLD_NUM INTEGER NOT NULL,
  HOLD_RATIO DOUBLE NOT NULL,
  HOLD_NUM_CHANGE INTEGER,
  HOLD_RATIO_CHANGE DOUBLE,
  DIRECTION VARCHAR NOT NULL,
  SHARES_TYPE VARCHAR NOT NULL,
  HOLDER_NATURE VARCHAR NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  HOLD_CHANGE VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  HOLD_RATIO_YOY DOUBLE,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  HOLDER_NEW VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  HOLDNUM_CHANGE_RATIO DOUBLE,
  IS_MAX_REPORTDATE VARCHAR NOT NULL,
  HOLDER_MARKET_CAP DOUBLE NOT NULL,
  HOLDNUM_CHANGE_NAME VARCHAR NOT NULL,
  MXID VARCHAR NOT NULL,
  HOLDER_NEWTYPE VARCHAR NOT NULL,
  XZCHANGE INTEGER,
  HOLDER_TYPE_ORG VARCHAR NOT NULL,
  HOLD_RATIO_DIRECTION VARCHAR NOT NULL,
  REFERENCE_MARKET_CAP DOUBLE NOT NULL,
  HOLD_ORG_CODE_SOURCE VARCHAR,
  LISTING_STATE VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, END_DATE, HOLDER_NAME, RANK)
);

CREATE INDEX IF NOT EXISTS idx_rpt_dmsk_holders_end_date ON rpt_dmsk_holders(END_DATE);
