-- ============================================================
-- RPT_DAILYBILLBOARD_DETAILSNEW
-- trading/龙虎榜单 (操盘版) (event)
-- 个股龙虎榜每日明细; chunky lhb_client 实际使用
-- 样本行数: 200, 字段数: 39
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_dailybillboard_detailsnew (
  TRADE_DATE TIMESTAMP NOT NULL,
  DEAL_AMOUNT_RATIO DOUBLE NOT NULL,
  BILLBOARD_DEAL_AMT DOUBLE NOT NULL,
  FREE_MARKET_CAP DOUBLE NOT NULL,
  EXPLAIN VARCHAR NOT NULL,
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  CLOSE_PRICE DOUBLE NOT NULL,
  CHANGE_RATE DOUBLE NOT NULL,
  TURNOVERRATE DOUBLE NOT NULL,
  D1_CLOSE_ADJCHRATE DOUBLE,
  D2_CLOSE_ADJCHRATE DOUBLE,
  D5_CLOSE_ADJCHRATE DOUBLE,
  D10_CLOSE_ADJCHRATE DOUBLE,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  EXPLANATION VARCHAR NOT NULL,
  BILLBOARD_SELL_AMT DOUBLE NOT NULL,
  BILLBOARD_BUY_AMT DOUBLE NOT NULL,
  SECURITY_INNER_CODE VARCHAR NOT NULL,
  BILLBOARD_NET_AMT DOUBLE NOT NULL,
  DEAL_NET_RATIO DOUBLE NOT NULL,
  ACCUM_AMOUNT DOUBLE NOT NULL,
  MARKET VARCHAR NOT NULL,
  CHANGE_TYPE VARCHAR NOT NULL,
  TRADE_ID INTEGER NOT NULL,
  BUY_SEAT INTEGER NOT NULL,
  SELL_SEAT INTEGER NOT NULL,
  BUY_RATIO DOUBLE NOT NULL,
  SELL_RATIO DOUBLE NOT NULL,
  TRADE_MARKET VARCHAR NOT NULL,
  D30_CLOSE_ADJCHRATE DOUBLE,
  D20_CLOSE_ADJCHRATE DOUBLE,
  TRADE_MARKET_CODE VARCHAR NOT NULL,
  BUY_SEAT_NEW VARCHAR NOT NULL,
  SELL_SEAT_NEW VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  SUM_BUY_AMT DOUBLE NOT NULL,
  SUM_SELL_AMT DOUBLE NOT NULL,
  NET_BS_AMT DOUBLE NOT NULL,
  PRIMARY KEY (SECUCODE, TRADE_DATE, EXPLANATION)
);

CREATE INDEX IF NOT EXISTS idx_rpt_dailybillboard_detailsnew_trade_date ON rpt_dailybillboard_detailsnew(TRADE_DATE);
