-- ============================================================
-- RPT_ORG_SURVEYNEW
-- research/机构调研 (特殊报表) (daily)
-- chunky institution_survey_client 实际使用; extra_filters: NOTICE_DATE 增量
-- 样本行数: 200, 字段数: 30
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_org_surveynew (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  RECEIVE_START_DATE TIMESTAMP NOT NULL,
  RECEIVE_END_DATE TIMESTAMP,
  RECEIVE_TIME_EXPLAIN VARCHAR NOT NULL,
  RECEIVE_OBJECT_TYPE VARCHAR NOT NULL,
  RECEIVE_OBJECT VARCHAR NOT NULL,
  OBJECT_CODE VARCHAR,
  END_DATE TIMESTAMP NOT NULL,
  SOURCE VARCHAR NOT NULL,
  RECEIVE_PLACE VARCHAR,
  RECEIVE_WAY VARCHAR NOT NULL,
  RECEIVE_WAY_EXPLAIN VARCHAR NOT NULL,
  INVESTIGATORS VARCHAR,
  RECEPTIONIST VARCHAR NOT NULL,
  -- REMARK: 全部样本为空, 默认 TEXT
  REMARK VARCHAR,
  NUM INTEGER NOT NULL,
  IS_MAX_REPORT VARCHAR NOT NULL,
  EUTIME TIMESTAMP NOT NULL,
  LISTING_STATE VARCHAR NOT NULL,
  SUM INTEGER NOT NULL,
  ORG_TYPE VARCHAR,
  ORG_NAME VARCHAR NOT NULL,
  EITIME TIMESTAMP NOT NULL,
  ORG_TYPE_CODE VARCHAR,
  IS_SOURCE VARCHAR NOT NULL,
  NUMBERNEW VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, NOTICE_DATE, RECEIVE_START_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_org_surveynew_notice_date ON rpt_org_surveynew(NOTICE_DATE);
